// Code generated by MockGen. DO NOT EDIT.
// Source: internal/transport/product/product.go
//
// Generated by this command:
//
//	mockgen -source=internal/transport/product/product.go -destination=internal/transport/product/product.mock.go -package=product
//

// Package product is a generated GoMock package.
package product

import (
	context "context"
	reflect "reflect"

	dto "github.com/jackvonhouse/product-catalog/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockproductUseCase is a mock of productUseCase interface.
type MockproductUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockproductUseCaseMockRecorder
}

// MockproductUseCaseMockRecorder is the mock recorder for MockproductUseCase.
type MockproductUseCaseMockRecorder struct {
	mock *MockproductUseCase
}

// NewMockproductUseCase creates a new mock instance.
func NewMockproductUseCase(ctrl *gomock.Controller) *MockproductUseCase {
	mock := &MockproductUseCase{ctrl: ctrl}
	mock.recorder = &MockproductUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproductUseCase) EXPECT() *MockproductUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockproductUseCase) Create(arg0 context.Context, arg1 dto.CreateProduct) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockproductUseCaseMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockproductUseCase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockproductUseCase) Delete(arg0 context.Context, arg1 int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockproductUseCaseMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockproductUseCase)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockproductUseCase) Get(arg0 context.Context, arg1 dto.GetProduct) ([]dto.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].([]dto.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockproductUseCaseMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockproductUseCase)(nil).Get), arg0, arg1)
}

// GetByCategoryId mocks base method.
func (m *MockproductUseCase) GetByCategoryId(arg0 context.Context, arg1 dto.GetProduct, arg2 int) ([]dto.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategoryId", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dto.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategoryId indicates an expected call of GetByCategoryId.
func (mr *MockproductUseCaseMockRecorder) GetByCategoryId(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategoryId", reflect.TypeOf((*MockproductUseCase)(nil).GetByCategoryId), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockproductUseCase) Update(arg0 context.Context, arg1 dto.UpdateProduct) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockproductUseCaseMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockproductUseCase)(nil).Update), arg0, arg1)
}

// MockuseCaseAccessToken is a mock of useCaseAccessToken interface.
type MockuseCaseAccessToken struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseAccessTokenMockRecorder
}

// MockuseCaseAccessTokenMockRecorder is the mock recorder for MockuseCaseAccessToken.
type MockuseCaseAccessTokenMockRecorder struct {
	mock *MockuseCaseAccessToken
}

// NewMockuseCaseAccessToken creates a new mock instance.
func NewMockuseCaseAccessToken(ctrl *gomock.Controller) *MockuseCaseAccessToken {
	mock := &MockuseCaseAccessToken{ctrl: ctrl}
	mock.recorder = &MockuseCaseAccessTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCaseAccessToken) EXPECT() *MockuseCaseAccessTokenMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockuseCaseAccessToken) Verify(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockuseCaseAccessTokenMockRecorder) Verify(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockuseCaseAccessToken)(nil).Verify), arg0, arg1)
}
